2018-11-18 19:10:10.261 [error] <0.318.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:01:59.405 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:02:28.275 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:02:38.276 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:02:48.278 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:02:58.279 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:02.240 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.293 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.303 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.295 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.357 [error] <0.364.0> gen_server <0.364.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.356 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.358 [error] <0.364.0> CRASH REPORT Process <0.364.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.356 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.360 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.364.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.361 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.366 [error] <0.365.0> gen_server <0.365.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.363 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.367 [error] <0.365.0> CRASH REPORT Process <0.365.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.364 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.368 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.365.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.370 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.374 [error] <0.366.0> gen_server <0.366.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.371 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.375 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.372 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.375 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.366.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.372 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.376 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.366.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:02.373 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.377 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:02.374 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.374 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:02.381 [error] <0.368.0> gen_server <0.368.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.381 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.375 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:02.378 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.383 [error] <0.367.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.368.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.386 [error] <0.369.0> gen_server <0.369.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.379 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.387 [error] <0.369.0> CRASH REPORT Process <0.369.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.380 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.384 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.388 [error] <0.367.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.369.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.384 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.394 [error] <0.370.0> gen_server <0.370.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.385 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.314.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.395 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.395 [error] <0.367.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.370.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.388 [error] <0.315.0> gen_server <0.315.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.407 [error] <0.371.0> gen_server <0.371.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.407 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.408 [error] <0.367.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.371.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.408 [error] <0.367.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.371.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:02.408 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.367.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:02.413 [error] <0.373.0> gen_server <0.373.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.414 [error] <0.373.0> CRASH REPORT Process <0.373.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.414 [error] <0.372.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.373.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.823 [error] <0.374.0> gen_server <0.374.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.823 [error] <0.374.0> CRASH REPORT Process <0.374.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.824 [error] <0.372.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.374.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:02.824 [error] <0.375.0> gen_server <0.375.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.824 [error] <0.375.0> CRASH REPORT Process <0.375.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:02.825 [error] <0.372.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.375.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:08.280 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:18.281 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:28.283 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:38.284 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:48.285 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:03:55.377 [error] <0.381.0> gen_server <0.381.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.379 [error] <0.381.0> CRASH REPORT Process <0.381.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.400 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.380 [error] <0.377.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.381.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.447 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.449 [error] <0.445.0> gen_server <0.445.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.451 [error] <0.445.0> CRASH REPORT Process <0.445.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.448 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.452 [error] <0.377.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.445.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.454 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.456 [error] <0.446.0> gen_server <0.446.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.454 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.458 [error] <0.446.0> CRASH REPORT Process <0.446.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.455 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.459 [error] <0.377.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.446.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.460 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.462 [error] <0.447.0> gen_server <0.447.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.461 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.463 [error] <0.447.0> CRASH REPORT Process <0.447.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.462 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.464 [error] <0.377.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.447.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.464 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.464 [error] <0.377.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.447.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:55.466 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.464 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.377.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:55.466 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.467 [error] <0.449.0> gen_server <0.449.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.467 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:55.468 [error] <0.449.0> CRASH REPORT Process <0.449.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.467 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:55.470 [error] <0.448.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.449.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.480 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.482 [error] <0.450.0> gen_server <0.450.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.481 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.483 [error] <0.450.0> CRASH REPORT Process <0.450.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.482 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.484 [error] <0.448.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.450.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.487 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.490 [error] <0.451.0> gen_server <0.451.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.491 [error] <0.451.0> CRASH REPORT Process <0.451.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.492 [error] <0.448.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.451.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.496 [error] <0.452.0> gen_server <0.452.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.497 [error] <0.452.0> CRASH REPORT Process <0.452.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.498 [error] <0.448.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.452.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.498 [error] <0.448.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.452.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:03:55.499 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.448.0> exit with reason shutdown in context child_terminated
2018-11-18 21:03:55.502 [error] <0.454.0> gen_server <0.454.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.504 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.504 [error] <0.453.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.454.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.510 [error] <0.455.0> gen_server <0.455.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.511 [error] <0.455.0> CRASH REPORT Process <0.455.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.511 [error] <0.453.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.455.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:55.514 [error] <0.456.0> gen_server <0.456.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.516 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:03:55.517 [error] <0.453.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.456.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:03:58.286 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:04:08.287 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:04:26.067 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.108 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.120 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.109 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.162 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.164 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.162 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.167 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.165 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.168 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.165 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.170 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.169 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.174 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.172 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.173 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.176 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.176 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.178 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.179 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.179 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.179 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.180 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.180 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:04:26.181 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.180 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:04:26.182 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:04:26.182 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:04:26.184 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.185 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.186 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.186 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.187 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.188 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.190 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.191 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.192 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.194 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.192 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.314.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.196 [error] <0.315.0> gen_server <0.315.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.195 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.314.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.198 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.199 [error] <0.315.0> gen_server <0.315.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.203 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.198 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.315.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.213 [error] <0.316.0> gen_server <0.316.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.204 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.315.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.214 [error] <0.316.0> gen_server <0.316.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.213 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.216 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.213 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.214 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:04:26.217 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.217 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:04:26.214 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.312.0> exit with reason shutdown in context child_terminated
2018-11-18 21:04:26.220 [error] <0.318.0> gen_server <0.318.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.218 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.312.0> exit with reason shutdown in context child_terminated
2018-11-18 21:04:26.221 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.221 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.318.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.226 [error] <0.319.0> gen_server <0.319.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.566 [error] <0.319.0> CRASH REPORT Process <0.319.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.567 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.319.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:04:26.567 [error] <0.320.0> gen_server <0.320.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.567 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:04:26.568 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.320.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:05:46.863 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node alice@mac2 is not yet connected during send!
2018-11-18 21:06:50.033 [error] <0.318.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:06:52.632 [error] <0.283.0>@partisan_default_peer_service_manager:do_send_message:1018 Node alice@mac2 is not yet connected during send!
2018-11-18 21:07:58.945 [error] <0.240.0> Supervisor partisan_sup had child partisan_default_peer_service_manager started with partisan_default_peer_service_manager:start_link() at <0.283.0> exit with reason normal in context child_terminated
2018-11-18 21:07:58.946 [error] <0.292.0> gen_server <0.292.0> terminated with reason: {normal,{gen_server,call,[partisan_default_peer_service_manager,{receive_message,{receive_state,#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},{state_orset,[{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},[{<<150,231,138,66,74,144,88,63,196,136,89,4,197,131,230,146,220,59,78,105>>,true}]},{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => ...}],...},...},...]}}},...]}} in gen_server:call/3 line 223
2018-11-18 21:07:58.979 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {normal,{gen_server,call,[partisan_default_peer_service_manager,{receive_message,{receive_state,#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},{state_orset,[{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},[{<<150,231,138,66,74,144,88,63,196,136,89,4,197,131,230,146,220,59,78,105>>,true}]},{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => ...}],...},...},...]}}},...]}} in gen_server:call/3 line 223
2018-11-18 21:07:58.979 [error] <0.289.0> Supervisor partisan_pool had child {partisan_peer_service_server,{{127,0,0,1},49454},
                              {{127,0,0,1},49447},
                              #Ref<0.1563530520.1427111937.137643>} started with {partisan_peer_service_server,acceptor_init,undefined} at <0.292.0> exit with reason {normal,{gen_server,call,[partisan_default_peer_service_manager,{receive_message,{receive_state,#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},{state_orset,[{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => 49419}],name => alice@mac2,parallelism => 1},[{<<150,231,138,66,74,144,88,63,196,136,89,4,197,131,230,146,220,59,78,105>>,true}]},{#{channels => [undefined],listen_addrs => [#{ip => {127,0,0,1},port => ...}],...},...},...]}}},...]}} in context child_terminated
2018-11-18 21:14:19.891 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:14:19.899 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:14:19.901 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.connect_node/1 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:14:20.942 [error] <0.324.0>@partisan_default_peer_service_manager:do_send_message:1018 Node alice@mac2 is not yet connected during send!
2018-11-18 21:15:19.824 [error] <0.318.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:15:29.825 [error] <0.318.0>@partisan_default_peer_service_manager:do_send_message:1018 Node bob@mac2 is not yet connected during send!
2018-11-18 21:15:36.191 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.237 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.249 [error] <0.306.0> gen_server <0.306.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.237 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.292 [error] <0.306.0> CRASH REPORT Process <0.306.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.293 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.294 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.295 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.293 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.306.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.297 [error] <0.309.0> gen_server <0.309.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.299 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.301 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.298 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.302 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.299 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.309.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.303 [error] <0.310.0> gen_server <0.310.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.307 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.308 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.304 [error] <0.310.0> CRASH REPORT Process <0.310.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.305 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.310.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.309 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.311 [error] <0.311.0> gen_server <0.311.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.309 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:15:36.313 [error] <0.311.0> CRASH REPORT Process <0.311.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.310 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:15:36.313 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.314 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.315 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.314 [error] <0.305.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.311.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:15:36.316 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.314 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.305.0> exit with reason shutdown in context child_terminated
2018-11-18 21:15:36.316 [error] <0.313.0> gen_server <0.313.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.320 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.321 [error] <0.314.0> CRASH REPORT Process <0.314.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.318 [error] <0.313.0> CRASH REPORT Process <0.313.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.319 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.313.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.322 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.314.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.326 [error] <0.315.0> gen_server <0.315.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.324 [error] <0.314.0> gen_server <0.314.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.327 [error] <0.315.0> CRASH REPORT Process <0.315.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.328 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.315.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.330 [error] <0.316.0> gen_server <0.316.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.331 [error] <0.316.0> CRASH REPORT Process <0.316.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.332 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.333 [error] <0.312.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.316.0> exit with reason reached_max_restart_intensity in context shutdown
2018-11-18 21:15:36.333 [error] <0.304.0> Supervisor 'Elixir.PC.Supervisor' had child 'Elixir.Cluster.Supervisor' started with 'Elixir.Cluster.Supervisor':start_link([[{example,[{strategy,'Elixir.Cluster.Strategy.Gossip'},{connect,{'Elixir.PC',connect_node,[]}},...]}],...]) at <0.312.0> exit with reason shutdown in context child_terminated
2018-11-18 21:15:36.338 [error] <0.318.0> gen_server <0.318.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.338 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.338 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.318.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.342 [error] <0.319.0> gen_server <0.319.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.344 [error] <0.319.0> CRASH REPORT Process <0.319.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.345 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.319.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
2018-11-18 21:15:36.347 [error] <0.320.0> gen_server <0.320.0> terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.348 [error] <0.320.0> CRASH REPORT Process <0.320.0> with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156
2018-11-18 21:15:36.349 [error] <0.317.0> Supervisor 'Elixir.PC.Cluster.Supervisor' had child 'Elixir.Cluster.Strategy.Gossip' started with 'Elixir.Cluster.Strategy.Gossip':start_link([#{'__struct__' => 'Elixir.Cluster.Strategy.State',config => [],connect => {'Elixir.PC',connect_node,...},...}]) at <0.320.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"Elixir.PC.list_nodes/0 is undefined!">>} in 'Elixir.Cluster.Strategy':'ensure_exported!'/3 line 156 in context child_terminated
